default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= 'localhost' %>
  port: <%= 5432 %>
  username: <%= ENV['POSTGRES_USER'] ? ENV['POSTGRES_USER'] : 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ? ENV['POSTGRES_PASSWORD'] : 'postgres' %>
  timeout: 5000

development:
  <<: *default
  database: bulk_insert_development

test:
  <<: *default
  database: bulk_insert_test
